#!/bin/sh

if [ ! -e /boot/wifi.txt ]
then
	echo "Wifi settings not found!"
	exit 0
fi

source /boot/wifi.txt

modprobe "$WIFI_MODULE"

cat > /etc/wpa_supplicant.conf << END
ctrl_interface=/var/run/wpa_supplicant
ap_scan=1

network={
	ssid="$WIFI_SSID"
	psk="$WIFI_PASSWORD"
	scan_ssid=1
	key_mgmt=WPA-PSK
}
END

cat > /etc/network/interfaces << END
auto lo
iface lo inet loopback

auto wlan0
iface wlan0 inet dhcp
wireless-essid "$WIFI_SSID"
pre-up wpa_supplicant -B -D wext -i wlan0 -c /etc/wpa_supplicant.conf
post-down killall -q wpa_supplicant
END
